import 'package:flutter/material.dart';
const primaryColor=Color(0xFFc53f3f);
const primaryDarkColor=Color(0xFF843a3c);
const primaryLightColor=Color(0xFFf3d9d9);
const textFieldCBackgroundColor=Color(0xFFF7F8F8);
//Text Color
const primaryTextColor=Color(0xFF877CC8);
const titleTextColor=Color(0xFF1D1617);
const subTitleTextColor=Color(0xFF7B6F72);
const lineTextColor=Color(0xffADA4A5);
const bottomTextColor=Color(0xFFFFFFFF);
String? token;